CREATE TABLE payments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id    VARCHAR(120)                            NOT NULL,
    amount         DECIMAL(19, 2)                          NOT NULL,
    currency       VARCHAR(10)                             NOT NULL,
    status         VARCHAR(30)                             NOT NULL,
    customer_email VARCHAR(180),
    raw_payload    JSONB,
    event_id       VARCHAR(120),
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    CONSTRAINT pk_payments PRIMARY KEY (id),
    CONSTRAINT uc_payments_externalid UNIQUE (external_id)
);

CREATE INDEX idx_payments_created_at ON payments (created_at);
CREATE INDEX idx_payments_event_id ON payments (event_id);

CREATE TABLE conversions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_id       BIGINT                                  NOT NULL,
    platform         VARCHAR(20)                             NOT NULL,
    value            DECIMAL(19, 2)                          NOT NULL,
    request_payload  JSONB,
    response_payload JSONB,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    CONSTRAINT pk_conversions PRIMARY KEY (id)
);

CREATE INDEX idx_conversions_created_at ON conversions (created_at);
CREATE INDEX idx_conversions_payment_id ON conversions (payment_id);
CREATE INDEX idx_conversions_platform ON conversions (platform);

CREATE UNIQUE INDEX ux_conversions_payment_platform ON conversions (payment_id, platform);

CREATE TABLE leads
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(180)                            NOT NULL,
    name        VARCHAR(180),
    source      VARCHAR(60),
    raw_payload JSONB,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    CONSTRAINT pk_leads PRIMARY KEY (id)
);

CREATE INDEX idx_leads_created_at ON leads (created_at);
CREATE INDEX idx_leads_email ON leads (email);
