-- V5__create_solana_payments.sql
-- Tracks Solana Pay payments from creation through on-chain confirmation

CREATE TABLE solana_payments
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reference        VARCHAR(64)                             NOT NULL,
    recipient_wallet VARCHAR(64)                             NOT NULL,
    amount           DECIMAL(19, 9)                          NOT NULL,
    currency         VARCHAR(64)                             NOT NULL DEFAULT 'SOL',
    spl_token        VARCHAR(64),
    status           VARCHAR(20)                             NOT NULL DEFAULT 'PENDING',
    tx_signature     VARCHAR(128),
    payment_id       BIGINT,
    merchant_id      BIGINT                                  NOT NULL REFERENCES merchants (id),
    customer_email   VARCHAR(180),
    label            VARCHAR(255),
    message          VARCHAR(500),
    created_at       TIMESTAMP WITH TIME ZONE                NOT NULL DEFAULT now(),
    confirmed_at     TIMESTAMP WITH TIME ZONE,
    expires_at       TIMESTAMP WITH TIME ZONE                NOT NULL,

    CONSTRAINT pk_solana_payments PRIMARY KEY (id),
    CONSTRAINT uc_solana_reference UNIQUE (reference)
);

CREATE INDEX idx_solana_reference  ON solana_payments (reference);
CREATE INDEX idx_solana_status     ON solana_payments (status);
CREATE INDEX idx_solana_merchant   ON solana_payments (merchant_id);
CREATE INDEX idx_solana_created_at ON solana_payments (created_at);

-- Partial index for the verification job — only scans PENDING rows
CREATE INDEX idx_solana_expires_at ON solana_payments (expires_at) WHERE status = 'PENDING';
